apiVersion: apps/v1
kind: Deployment
metadata:
  name: command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command
  template:
    metadata:
      labels:
        app: command
    spec:
      containers:
      - name: command
        image: home-core/command-svc:1.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 9004
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: amq_host
          value: amq
        - name: SPRING_PROFILES_ACTIVE
          value: production
