apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  labels:
    app: cassandra-svc
spec:
  type: NodePort
  ports:
  - port: 9042
    name: cassandra-svc-port1
    targetPort: 9042
    nodePort: 30042
    protocol: TCP
  - port: 9160
    name: cassandra-svc-port2
    targetPort: 9160
    nodePort: 30096
    protocol: TCP
  selector:
    app: cassandra
