amq.producer.topic: states
amq.host: tcp://localhost:61616
amq.consumer.topic: commands
mqtt.host: tcp://mqtt.robot.renarj.nl:1883
server.port: 9005
---
spring:
    profiles: production
amq:
  host: ${amq_host}
  producer:
    topic: states
  consumer:
    topic: commands
mqtt:
  host: ${mqtt_host}
  port: ${mqtt_port}
server:
  port: 9005