amq.producer.topic: commands
amq.host: tcp://localhost:61616
server.port: 9004
management.security.enabled: false
---
spring:
    profiles: production
amq:
  host: ${amq_host}
  producer:
    topic: commands
server:
  port: 9004