amq.host: amq.robot.renarj.nl:9092
amq.consumer.topic: states
cassandra.host: localhost
cassandra.port: 9160
spring.main.web-environment: true
server.port: 9003
---
spring:
    profiles: production
amq:
  host: ${amq_host}
  consumer:
    topic: states
server:
  port: 8080
cassandra:
  host: ${cassandra_host}
  port: 9042
